---

- name: Inventory validation
  hosts: localhost
  gather_facts: false
  tasks:
    - assert:
        that:
          - "groups['serv'] | length >= 1"
          - "groups['client'] | length >= 1"
          - "groups['peerer'] | length == 1"
    - assert: { that: "'{{ item }}' not in groups['serv']" }
      with_items: "{{ groups['peerer'] }}"

- hosts: all
  gather_facts: False
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal python-apt)

- hosts: all
  become: true
  tasks:
    - name: "Install pre-req"
      apt:
        name:
          - python
          - software-properties-common
          - build-essential
          - wget
          - curl
        state: present
        update_cache: yes

    - name: "Add glusterfs 5 repo"
      apt_repository:
        repo: ppa:gluster/glusterfs-5
        state: present

- hosts: serv,peerer
  become: true
  tasks:
    - name: "Install gluster 5 server"
      apt:
        name:
          - glusterfs-server
        state: present
        update_cache: yes
    
    - name: "Upload etc hosts"
      template: src=etc-hosts.j2 dest=/etc/hosts mode=0755

    - name: enable glusterd service
      systemd:
        name: glusterd
        state: started
        enabled: yes

- hosts: peerer
  become: true
  tasks:
    - name: Peering with {{ item }}
      shell: gluster peer probe {{ item }}
      with_items:
        - "{{ groups['serv'] }}"

    - name: "Check peer status"
      shell: "gluster peer status"
      register: glsout

    - debug: var=glsout.stdout_lines

- hosts: client
  become: true
  tasks:
    - name: "Install gluster 5 client"
      apt:
        name:
          - glusterfs-client
        state: present
        update_cache: yes
        